package com.lmy.rsck.model.example;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.cheers.micro.common.vo.utils.StringUtils;
import com.cheers.micro.common.vo.utils.CollectionUtils;
import com.lmy.rsck.view.query.RsdfEventOptionPropertyQuery;
/**
 * 事件-属性变动表(RsdfEventOptionProperty)Example
 *
 * @author makejava
 * @since 2023-03-19 21:00:04
 */
public class RsdfEventOptionPropertyExample {
    public static Wrapper<RsdfEventOptionProperty> getWrapper(RsdfEventOptionPropertyQuery rsdfEventOptionPropertyQuery){
        QueryWrapper<RsdfEventOptionProperty> wrapper = new QueryWrapper();
                if(rsdfEventOptionPropertyQuery.getId()!=null){
            wrapper.lambda().eq(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getId());
        }
        if(rsdfEventOptionPropertyQuery.getIdNotEq()!=null){
            wrapper.lambda().ne(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdNotEq());
        }
        if(rsdfEventOptionPropertyQuery.getIdStart()!=null&&rsdfEventOptionPropertyQuery.getIdEnd()!=null){
            wrapper.lambda().between(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdStart(),rsdfEventOptionPropertyQuery.getIdEnd());
        }
        if(rsdfEventOptionPropertyQuery.getIdLessThan()!=null){
            wrapper.lambda().lt(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdLessThan());
        }
        if(rsdfEventOptionPropertyQuery.getIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdLessThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.getIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdGreaterThan());
        }
        if(rsdfEventOptionPropertyQuery.getIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdGreaterThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.isIdIsNull()){
            wrapper.lambda().isNull(RsdfEventOptionProperty::getId);
        }
        if(rsdfEventOptionPropertyQuery.isIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventOptionProperty::getId);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getIdList())){
            wrapper.lambda().in(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getIdNotInList())){
            wrapper.lambda().notIn(RsdfEventOptionProperty::getId,rsdfEventOptionPropertyQuery.getIdNotInList());
        }
            /**
         * 目标id
         */
            if(rsdfEventOptionPropertyQuery.getOptionId()!=null){
            wrapper.lambda().eq(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionId());
        }
        if(rsdfEventOptionPropertyQuery.getOptionIdNotEq()!=null){
            wrapper.lambda().ne(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdNotEq());
        }
        if(rsdfEventOptionPropertyQuery.getOptionIdStart()!=null&&rsdfEventOptionPropertyQuery.getOptionIdEnd()!=null){
            wrapper.lambda().between(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdStart(),rsdfEventOptionPropertyQuery.getOptionIdEnd());
        }
        if(rsdfEventOptionPropertyQuery.getOptionIdLessThan()!=null){
            wrapper.lambda().lt(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdLessThan());
        }
        if(rsdfEventOptionPropertyQuery.getOptionIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdLessThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.getOptionIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdGreaterThan());
        }
        if(rsdfEventOptionPropertyQuery.getOptionIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdGreaterThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.isOptionIdIsNull()){
            wrapper.lambda().isNull(RsdfEventOptionProperty::getOptionId);
        }
        if(rsdfEventOptionPropertyQuery.isOptionIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventOptionProperty::getOptionId);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getOptionIdList())){
            wrapper.lambda().in(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getOptionIdNotInList())){
            wrapper.lambda().notIn(RsdfEventOptionProperty::getOptionId,rsdfEventOptionPropertyQuery.getOptionIdNotInList());
        }
            /**
         * 属性id
         */
            if(rsdfEventOptionPropertyQuery.getPropertyId()!=null){
            wrapper.lambda().eq(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyId());
        }
        if(rsdfEventOptionPropertyQuery.getPropertyIdNotEq()!=null){
            wrapper.lambda().ne(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdNotEq());
        }
        if(rsdfEventOptionPropertyQuery.getPropertyIdStart()!=null&&rsdfEventOptionPropertyQuery.getPropertyIdEnd()!=null){
            wrapper.lambda().between(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdStart(),rsdfEventOptionPropertyQuery.getPropertyIdEnd());
        }
        if(rsdfEventOptionPropertyQuery.getPropertyIdLessThan()!=null){
            wrapper.lambda().lt(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdLessThan());
        }
        if(rsdfEventOptionPropertyQuery.getPropertyIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdLessThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.getPropertyIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdGreaterThan());
        }
        if(rsdfEventOptionPropertyQuery.getPropertyIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdGreaterThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.isPropertyIdIsNull()){
            wrapper.lambda().isNull(RsdfEventOptionProperty::getPropertyId);
        }
        if(rsdfEventOptionPropertyQuery.isPropertyIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventOptionProperty::getPropertyId);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getPropertyIdList())){
            wrapper.lambda().in(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getPropertyIdNotInList())){
            wrapper.lambda().notIn(RsdfEventOptionProperty::getPropertyId,rsdfEventOptionPropertyQuery.getPropertyIdNotInList());
        }
            /**
         * 变动最小值
         */
            if(rsdfEventOptionPropertyQuery.getMinValue()!=null){
            wrapper.lambda().eq(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValue());
        }
        if(rsdfEventOptionPropertyQuery.getMinValueNotEq()!=null){
            wrapper.lambda().ne(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueNotEq());
        }
        if(rsdfEventOptionPropertyQuery.getMinValueStart()!=null&&rsdfEventOptionPropertyQuery.getMinValueEnd()!=null){
            wrapper.lambda().between(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueStart(),rsdfEventOptionPropertyQuery.getMinValueEnd());
        }
        if(rsdfEventOptionPropertyQuery.getMinValueLessThan()!=null){
            wrapper.lambda().lt(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueLessThan());
        }
        if(rsdfEventOptionPropertyQuery.getMinValueLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueLessThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.getMinValueGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueGreaterThan());
        }
        if(rsdfEventOptionPropertyQuery.getMinValueGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueGreaterThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.isMinValueIsNull()){
            wrapper.lambda().isNull(RsdfEventOptionProperty::getMinValue);
        }
        if(rsdfEventOptionPropertyQuery.isMinValueIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventOptionProperty::getMinValue);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getMinValueList())){
            wrapper.lambda().in(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getMinValueNotInList())){
            wrapper.lambda().notIn(RsdfEventOptionProperty::getMinValue,rsdfEventOptionPropertyQuery.getMinValueNotInList());
        }
            /**
         * 变动最大值
         */
            if(rsdfEventOptionPropertyQuery.getMaxValue()!=null){
            wrapper.lambda().eq(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValue());
        }
        if(rsdfEventOptionPropertyQuery.getMaxValueNotEq()!=null){
            wrapper.lambda().ne(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueNotEq());
        }
        if(rsdfEventOptionPropertyQuery.getMaxValueStart()!=null&&rsdfEventOptionPropertyQuery.getMaxValueEnd()!=null){
            wrapper.lambda().between(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueStart(),rsdfEventOptionPropertyQuery.getMaxValueEnd());
        }
        if(rsdfEventOptionPropertyQuery.getMaxValueLessThan()!=null){
            wrapper.lambda().lt(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueLessThan());
        }
        if(rsdfEventOptionPropertyQuery.getMaxValueLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueLessThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.getMaxValueGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueGreaterThan());
        }
        if(rsdfEventOptionPropertyQuery.getMaxValueGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueGreaterThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.isMaxValueIsNull()){
            wrapper.lambda().isNull(RsdfEventOptionProperty::getMaxValue);
        }
        if(rsdfEventOptionPropertyQuery.isMaxValueIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventOptionProperty::getMaxValue);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getMaxValueList())){
            wrapper.lambda().in(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getMaxValueNotInList())){
            wrapper.lambda().notIn(RsdfEventOptionProperty::getMaxValue,rsdfEventOptionPropertyQuery.getMaxValueNotInList());
        }
            /**
         * 0=加减 1=百分比
         */
            if(rsdfEventOptionPropertyQuery.getChangeType()!=null){
            wrapper.lambda().eq(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeType());
        }
        if(rsdfEventOptionPropertyQuery.getChangeTypeNotEq()!=null){
            wrapper.lambda().ne(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeNotEq());
        }
        if(rsdfEventOptionPropertyQuery.getChangeTypeStart()!=null&&rsdfEventOptionPropertyQuery.getChangeTypeEnd()!=null){
            wrapper.lambda().between(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeStart(),rsdfEventOptionPropertyQuery.getChangeTypeEnd());
        }
        if(rsdfEventOptionPropertyQuery.getChangeTypeLessThan()!=null){
            wrapper.lambda().lt(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeLessThan());
        }
        if(rsdfEventOptionPropertyQuery.getChangeTypeLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeLessThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.getChangeTypeGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeGreaterThan());
        }
        if(rsdfEventOptionPropertyQuery.getChangeTypeGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeGreaterThanOrEqualTo());
        }
        if(rsdfEventOptionPropertyQuery.isChangeTypeIsNull()){
            wrapper.lambda().isNull(RsdfEventOptionProperty::getChangeType);
        }
        if(rsdfEventOptionPropertyQuery.isChangeTypeIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventOptionProperty::getChangeType);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getChangeTypeList())){
            wrapper.lambda().in(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventOptionPropertyQuery.getChangeTypeNotInList())){
            wrapper.lambda().notIn(RsdfEventOptionProperty::getChangeType,rsdfEventOptionPropertyQuery.getChangeTypeNotInList());
        }
        if(StringUtils.isNotBlank(rsdfEventOptionPropertyQuery.getOrderByColumn())){
            if(rsdfEventOptionPropertyQuery.isAes()){
                wrapper.orderByAsc(rsdfEventOptionPropertyQuery.getOrderByColumn());
            }else{
                wrapper.orderByDesc(rsdfEventOptionPropertyQuery.getOrderByColumn());
            }
        }
        return wrapper;
    }
}