package com.lmy.rsck.model.example;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.cheers.micro.common.vo.utils.StringUtils;
import com.cheers.micro.common.vo.utils.CollectionUtils;
import com.lmy.rsck.view.query.RsdfEventProbabilityPropertyQuery;
/**
 * 事件-属性概率表(RsdfEventProbabilityProperty)Example
 *
 * @author makejava
 * @since 2023-03-19 21:00:04
 */
public class RsdfEventProbabilityPropertyExample {
    public static Wrapper<RsdfEventProbabilityProperty> getWrapper(RsdfEventProbabilityPropertyQuery rsdfEventProbabilityPropertyQuery){
        QueryWrapper<RsdfEventProbabilityProperty> wrapper = new QueryWrapper();
                if(rsdfEventProbabilityPropertyQuery.getId()!=null){
            wrapper.lambda().eq(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getId());
        }
        if(rsdfEventProbabilityPropertyQuery.getIdNotEq()!=null){
            wrapper.lambda().ne(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdNotEq());
        }
        if(rsdfEventProbabilityPropertyQuery.getIdStart()!=null&&rsdfEventProbabilityPropertyQuery.getIdEnd()!=null){
            wrapper.lambda().between(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdStart(),rsdfEventProbabilityPropertyQuery.getIdEnd());
        }
        if(rsdfEventProbabilityPropertyQuery.getIdLessThan()!=null){
            wrapper.lambda().lt(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdLessThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdLessThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.getIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdGreaterThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdGreaterThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.isIdIsNull()){
            wrapper.lambda().isNull(RsdfEventProbabilityProperty::getId);
        }
        if(rsdfEventProbabilityPropertyQuery.isIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventProbabilityProperty::getId);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getIdList())){
            wrapper.lambda().in(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getIdNotInList())){
            wrapper.lambda().notIn(RsdfEventProbabilityProperty::getId,rsdfEventProbabilityPropertyQuery.getIdNotInList());
        }
            /**
         * 事件id
         */
            if(rsdfEventProbabilityPropertyQuery.getEventId()!=null){
            wrapper.lambda().eq(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventId());
        }
        if(rsdfEventProbabilityPropertyQuery.getEventIdNotEq()!=null){
            wrapper.lambda().ne(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdNotEq());
        }
        if(rsdfEventProbabilityPropertyQuery.getEventIdStart()!=null&&rsdfEventProbabilityPropertyQuery.getEventIdEnd()!=null){
            wrapper.lambda().between(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdStart(),rsdfEventProbabilityPropertyQuery.getEventIdEnd());
        }
        if(rsdfEventProbabilityPropertyQuery.getEventIdLessThan()!=null){
            wrapper.lambda().lt(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdLessThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getEventIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdLessThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.getEventIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdGreaterThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getEventIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdGreaterThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.isEventIdIsNull()){
            wrapper.lambda().isNull(RsdfEventProbabilityProperty::getEventId);
        }
        if(rsdfEventProbabilityPropertyQuery.isEventIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventProbabilityProperty::getEventId);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getEventIdList())){
            wrapper.lambda().in(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getEventIdNotInList())){
            wrapper.lambda().notIn(RsdfEventProbabilityProperty::getEventId,rsdfEventProbabilityPropertyQuery.getEventIdNotInList());
        }
            /**
         * 属性id
         */
            if(rsdfEventProbabilityPropertyQuery.getPropertyId()!=null){
            wrapper.lambda().eq(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyId());
        }
        if(rsdfEventProbabilityPropertyQuery.getPropertyIdNotEq()!=null){
            wrapper.lambda().ne(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdNotEq());
        }
        if(rsdfEventProbabilityPropertyQuery.getPropertyIdStart()!=null&&rsdfEventProbabilityPropertyQuery.getPropertyIdEnd()!=null){
            wrapper.lambda().between(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdStart(),rsdfEventProbabilityPropertyQuery.getPropertyIdEnd());
        }
        if(rsdfEventProbabilityPropertyQuery.getPropertyIdLessThan()!=null){
            wrapper.lambda().lt(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdLessThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getPropertyIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdLessThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.getPropertyIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdGreaterThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getPropertyIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdGreaterThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.isPropertyIdIsNull()){
            wrapper.lambda().isNull(RsdfEventProbabilityProperty::getPropertyId);
        }
        if(rsdfEventProbabilityPropertyQuery.isPropertyIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventProbabilityProperty::getPropertyId);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getPropertyIdList())){
            wrapper.lambda().in(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getPropertyIdNotInList())){
            wrapper.lambda().notIn(RsdfEventProbabilityProperty::getPropertyId,rsdfEventProbabilityPropertyQuery.getPropertyIdNotInList());
        }
            /**
         * 最小值
         */
            if(rsdfEventProbabilityPropertyQuery.getMinValue()!=null){
            wrapper.lambda().eq(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValue());
        }
        if(rsdfEventProbabilityPropertyQuery.getMinValueNotEq()!=null){
            wrapper.lambda().ne(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueNotEq());
        }
        if(rsdfEventProbabilityPropertyQuery.getMinValueStart()!=null&&rsdfEventProbabilityPropertyQuery.getMinValueEnd()!=null){
            wrapper.lambda().between(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueStart(),rsdfEventProbabilityPropertyQuery.getMinValueEnd());
        }
        if(rsdfEventProbabilityPropertyQuery.getMinValueLessThan()!=null){
            wrapper.lambda().lt(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueLessThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getMinValueLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueLessThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.getMinValueGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueGreaterThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getMinValueGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueGreaterThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.isMinValueIsNull()){
            wrapper.lambda().isNull(RsdfEventProbabilityProperty::getMinValue);
        }
        if(rsdfEventProbabilityPropertyQuery.isMinValueIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventProbabilityProperty::getMinValue);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getMinValueList())){
            wrapper.lambda().in(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getMinValueNotInList())){
            wrapper.lambda().notIn(RsdfEventProbabilityProperty::getMinValue,rsdfEventProbabilityPropertyQuery.getMinValueNotInList());
        }
            /**
         * 最大值
         */
            if(rsdfEventProbabilityPropertyQuery.getMaxValue()!=null){
            wrapper.lambda().eq(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValue());
        }
        if(rsdfEventProbabilityPropertyQuery.getMaxValueNotEq()!=null){
            wrapper.lambda().ne(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueNotEq());
        }
        if(rsdfEventProbabilityPropertyQuery.getMaxValueStart()!=null&&rsdfEventProbabilityPropertyQuery.getMaxValueEnd()!=null){
            wrapper.lambda().between(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueStart(),rsdfEventProbabilityPropertyQuery.getMaxValueEnd());
        }
        if(rsdfEventProbabilityPropertyQuery.getMaxValueLessThan()!=null){
            wrapper.lambda().lt(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueLessThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getMaxValueLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueLessThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.getMaxValueGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueGreaterThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getMaxValueGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueGreaterThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.isMaxValueIsNull()){
            wrapper.lambda().isNull(RsdfEventProbabilityProperty::getMaxValue);
        }
        if(rsdfEventProbabilityPropertyQuery.isMaxValueIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventProbabilityProperty::getMaxValue);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getMaxValueList())){
            wrapper.lambda().in(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getMaxValueNotInList())){
            wrapper.lambda().notIn(RsdfEventProbabilityProperty::getMaxValue,rsdfEventProbabilityPropertyQuery.getMaxValueNotInList());
        }
            /**
         * 系数
         */
            if(rsdfEventProbabilityPropertyQuery.getRatio()!=null){
            wrapper.lambda().eq(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatio());
        }
        if(rsdfEventProbabilityPropertyQuery.getRatioNotEq()!=null){
            wrapper.lambda().ne(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioNotEq());
        }
        if(rsdfEventProbabilityPropertyQuery.getRatioStart()!=null&&rsdfEventProbabilityPropertyQuery.getRatioEnd()!=null){
            wrapper.lambda().between(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioStart(),rsdfEventProbabilityPropertyQuery.getRatioEnd());
        }
        if(rsdfEventProbabilityPropertyQuery.getRatioLessThan()!=null){
            wrapper.lambda().lt(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioLessThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getRatioLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioLessThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.getRatioGreaterThan()!=null){
            wrapper.lambda().gt(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioGreaterThan());
        }
        if(rsdfEventProbabilityPropertyQuery.getRatioGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioGreaterThanOrEqualTo());
        }
        if(rsdfEventProbabilityPropertyQuery.isRatioIsNull()){
            wrapper.lambda().isNull(RsdfEventProbabilityProperty::getRatio);
        }
        if(rsdfEventProbabilityPropertyQuery.isRatioIsNotNull()){
            wrapper.lambda().isNotNull(RsdfEventProbabilityProperty::getRatio);
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getRatioList())){
            wrapper.lambda().in(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioList());
        }
        if(CollectionUtils.isNotEmpty(rsdfEventProbabilityPropertyQuery.getRatioNotInList())){
            wrapper.lambda().notIn(RsdfEventProbabilityProperty::getRatio,rsdfEventProbabilityPropertyQuery.getRatioNotInList());
        }
        if(StringUtils.isNotBlank(rsdfEventProbabilityPropertyQuery.getOrderByColumn())){
            if(rsdfEventProbabilityPropertyQuery.isAes()){
                wrapper.orderByAsc(rsdfEventProbabilityPropertyQuery.getOrderByColumn());
            }else{
                wrapper.orderByDesc(rsdfEventProbabilityPropertyQuery.getOrderByColumn());
            }
        }
        return wrapper;
    }
}