package com.lmy.rsck.model.example;

import java.util.Date;
import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.cheers.micro.common.vo.utils.StringUtils;
import com.cheers.micro.common.vo.utils.CollectionUtils;
import com.lmy.rsck.view.query.RsdfGamePropertyRecordQuery;
/**
 * 属性变动记录表(RsdfGamePropertyRecord)Example
 *
 * @author makejava
 * @since 2023-03-19 21:00:05
 */
public class RsdfGamePropertyRecordExample {
    public static Wrapper<RsdfGamePropertyRecord> getWrapper(RsdfGamePropertyRecordQuery rsdfGamePropertyRecordQuery){
        QueryWrapper<RsdfGamePropertyRecord> wrapper = new QueryWrapper();
                if(rsdfGamePropertyRecordQuery.getId()!=null){
            wrapper.lambda().eq(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getId());
        }
        if(rsdfGamePropertyRecordQuery.getIdNotEq()!=null){
            wrapper.lambda().ne(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdNotEq());
        }
        if(rsdfGamePropertyRecordQuery.getIdStart()!=null&&rsdfGamePropertyRecordQuery.getIdEnd()!=null){
            wrapper.lambda().between(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdStart(),rsdfGamePropertyRecordQuery.getIdEnd());
        }
        if(rsdfGamePropertyRecordQuery.getIdLessThan()!=null){
            wrapper.lambda().lt(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdLessThan());
        }
        if(rsdfGamePropertyRecordQuery.getIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdLessThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.getIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdGreaterThan());
        }
        if(rsdfGamePropertyRecordQuery.getIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdGreaterThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.isIdIsNull()){
            wrapper.lambda().isNull(RsdfGamePropertyRecord::getId);
        }
        if(rsdfGamePropertyRecordQuery.isIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfGamePropertyRecord::getId);
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getIdList())){
            wrapper.lambda().in(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getIdNotInList())){
            wrapper.lambda().notIn(RsdfGamePropertyRecord::getId,rsdfGamePropertyRecordQuery.getIdNotInList());
        }
            /**
         * 游戏属性id
         */
            if(rsdfGamePropertyRecordQuery.getGamePropertyId()!=null){
            wrapper.lambda().eq(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyId());
        }
        if(rsdfGamePropertyRecordQuery.getGamePropertyIdNotEq()!=null){
            wrapper.lambda().ne(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdNotEq());
        }
        if(rsdfGamePropertyRecordQuery.getGamePropertyIdStart()!=null&&rsdfGamePropertyRecordQuery.getGamePropertyIdEnd()!=null){
            wrapper.lambda().between(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdStart(),rsdfGamePropertyRecordQuery.getGamePropertyIdEnd());
        }
        if(rsdfGamePropertyRecordQuery.getGamePropertyIdLessThan()!=null){
            wrapper.lambda().lt(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdLessThan());
        }
        if(rsdfGamePropertyRecordQuery.getGamePropertyIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdLessThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.getGamePropertyIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdGreaterThan());
        }
        if(rsdfGamePropertyRecordQuery.getGamePropertyIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdGreaterThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.isGamePropertyIdIsNull()){
            wrapper.lambda().isNull(RsdfGamePropertyRecord::getGamePropertyId);
        }
        if(rsdfGamePropertyRecordQuery.isGamePropertyIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfGamePropertyRecord::getGamePropertyId);
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getGamePropertyIdList())){
            wrapper.lambda().in(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getGamePropertyIdNotInList())){
            wrapper.lambda().notIn(RsdfGamePropertyRecord::getGamePropertyId,rsdfGamePropertyRecordQuery.getGamePropertyIdNotInList());
        }
            /**
         * 时间id
         */
            if(rsdfGamePropertyRecordQuery.getTimeId()!=null){
            wrapper.lambda().eq(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeId());
        }
        if(rsdfGamePropertyRecordQuery.getTimeIdNotEq()!=null){
            wrapper.lambda().ne(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdNotEq());
        }
        if(rsdfGamePropertyRecordQuery.getTimeIdStart()!=null&&rsdfGamePropertyRecordQuery.getTimeIdEnd()!=null){
            wrapper.lambda().between(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdStart(),rsdfGamePropertyRecordQuery.getTimeIdEnd());
        }
        if(rsdfGamePropertyRecordQuery.getTimeIdLessThan()!=null){
            wrapper.lambda().lt(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdLessThan());
        }
        if(rsdfGamePropertyRecordQuery.getTimeIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdLessThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.getTimeIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdGreaterThan());
        }
        if(rsdfGamePropertyRecordQuery.getTimeIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdGreaterThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.isTimeIdIsNull()){
            wrapper.lambda().isNull(RsdfGamePropertyRecord::getTimeId);
        }
        if(rsdfGamePropertyRecordQuery.isTimeIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfGamePropertyRecord::getTimeId);
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getTimeIdList())){
            wrapper.lambda().in(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getTimeIdNotInList())){
            wrapper.lambda().notIn(RsdfGamePropertyRecord::getTimeId,rsdfGamePropertyRecordQuery.getTimeIdNotInList());
        }
            /**
         * 属性值
         */
            if(rsdfGamePropertyRecordQuery.getValue()!=null){
            wrapper.lambda().eq(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValue());
        }
        if(rsdfGamePropertyRecordQuery.getValueNotEq()!=null){
            wrapper.lambda().ne(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueNotEq());
        }
        if(rsdfGamePropertyRecordQuery.getValueStart()!=null&&rsdfGamePropertyRecordQuery.getValueEnd()!=null){
            wrapper.lambda().between(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueStart(),rsdfGamePropertyRecordQuery.getValueEnd());
        }
        if(rsdfGamePropertyRecordQuery.getValueLessThan()!=null){
            wrapper.lambda().lt(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueLessThan());
        }
        if(rsdfGamePropertyRecordQuery.getValueLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueLessThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.getValueGreaterThan()!=null){
            wrapper.lambda().gt(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueGreaterThan());
        }
        if(rsdfGamePropertyRecordQuery.getValueGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueGreaterThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.isValueIsNull()){
            wrapper.lambda().isNull(RsdfGamePropertyRecord::getValue);
        }
        if(rsdfGamePropertyRecordQuery.isValueIsNotNull()){
            wrapper.lambda().isNotNull(RsdfGamePropertyRecord::getValue);
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getValueList())){
            wrapper.lambda().in(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueList());
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getValueNotInList())){
            wrapper.lambda().notIn(RsdfGamePropertyRecord::getValue,rsdfGamePropertyRecordQuery.getValueNotInList());
        }
            /**
         * 来源
         */
            if(rsdfGamePropertyRecordQuery.getSource()!=null){
            wrapper.lambda().eq(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSource());
        }
        if(rsdfGamePropertyRecordQuery.getSourceNotEq()!=null){
            wrapper.lambda().ne(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceNotEq());
        }
        if(rsdfGamePropertyRecordQuery.getSourceStart()!=null&&rsdfGamePropertyRecordQuery.getSourceEnd()!=null){
            wrapper.lambda().between(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceStart(),rsdfGamePropertyRecordQuery.getSourceEnd());
        }
        if(rsdfGamePropertyRecordQuery.getSourceLessThan()!=null){
            wrapper.lambda().lt(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceLessThan());
        }
        if(rsdfGamePropertyRecordQuery.getSourceLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceLessThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.getSourceGreaterThan()!=null){
            wrapper.lambda().gt(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceGreaterThan());
        }
        if(rsdfGamePropertyRecordQuery.getSourceGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceGreaterThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.isSourceIsNull()){
            wrapper.lambda().isNull(RsdfGamePropertyRecord::getSource);
        }
        if(rsdfGamePropertyRecordQuery.isSourceIsNotNull()){
            wrapper.lambda().isNotNull(RsdfGamePropertyRecord::getSource);
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getSourceList())){
            wrapper.lambda().in(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceList());
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getSourceNotInList())){
            wrapper.lambda().notIn(RsdfGamePropertyRecord::getSource,rsdfGamePropertyRecordQuery.getSourceNotInList());
        }
            /**
         * 来源id
         */
            if(rsdfGamePropertyRecordQuery.getSourceId()!=null){
            wrapper.lambda().eq(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceId());
        }
        if(rsdfGamePropertyRecordQuery.getSourceIdNotEq()!=null){
            wrapper.lambda().ne(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdNotEq());
        }
        if(rsdfGamePropertyRecordQuery.getSourceIdStart()!=null&&rsdfGamePropertyRecordQuery.getSourceIdEnd()!=null){
            wrapper.lambda().between(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdStart(),rsdfGamePropertyRecordQuery.getSourceIdEnd());
        }
        if(rsdfGamePropertyRecordQuery.getSourceIdLessThan()!=null){
            wrapper.lambda().lt(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdLessThan());
        }
        if(rsdfGamePropertyRecordQuery.getSourceIdLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdLessThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.getSourceIdGreaterThan()!=null){
            wrapper.lambda().gt(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdGreaterThan());
        }
        if(rsdfGamePropertyRecordQuery.getSourceIdGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdGreaterThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.isSourceIdIsNull()){
            wrapper.lambda().isNull(RsdfGamePropertyRecord::getSourceId);
        }
        if(rsdfGamePropertyRecordQuery.isSourceIdIsNotNull()){
            wrapper.lambda().isNotNull(RsdfGamePropertyRecord::getSourceId);
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getSourceIdList())){
            wrapper.lambda().in(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdList());
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getSourceIdNotInList())){
            wrapper.lambda().notIn(RsdfGamePropertyRecord::getSourceId,rsdfGamePropertyRecordQuery.getSourceIdNotInList());
        }
            /**
         * 发生时间
         */
            if(rsdfGamePropertyRecordQuery.getCreatedTime()!=null){
            wrapper.lambda().eq(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTime());
        }
        if(rsdfGamePropertyRecordQuery.getCreatedTimeNotEq()!=null){
            wrapper.lambda().ne(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeNotEq());
        }
        if(rsdfGamePropertyRecordQuery.getCreatedTimeStart()!=null&&rsdfGamePropertyRecordQuery.getCreatedTimeEnd()!=null){
            wrapper.lambda().between(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeStart(),rsdfGamePropertyRecordQuery.getCreatedTimeEnd());
        }
        if(rsdfGamePropertyRecordQuery.getCreatedTimeLessThan()!=null){
            wrapper.lambda().lt(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeLessThan());
        }
        if(rsdfGamePropertyRecordQuery.getCreatedTimeLessThanOrEqualTo()!=null){
            wrapper.lambda().le(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeLessThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.getCreatedTimeGreaterThan()!=null){
            wrapper.lambda().gt(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeGreaterThan());
        }
        if(rsdfGamePropertyRecordQuery.getCreatedTimeGreaterThanOrEqualTo()!=null){
            wrapper.lambda().ge(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeGreaterThanOrEqualTo());
        }
        if(rsdfGamePropertyRecordQuery.isCreatedTimeIsNull()){
            wrapper.lambda().isNull(RsdfGamePropertyRecord::getCreatedTime);
        }
        if(rsdfGamePropertyRecordQuery.isCreatedTimeIsNotNull()){
            wrapper.lambda().isNotNull(RsdfGamePropertyRecord::getCreatedTime);
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getCreatedTimeList())){
            wrapper.lambda().in(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeList());
        }
        if(CollectionUtils.isNotEmpty(rsdfGamePropertyRecordQuery.getCreatedTimeNotInList())){
            wrapper.lambda().notIn(RsdfGamePropertyRecord::getCreatedTime,rsdfGamePropertyRecordQuery.getCreatedTimeNotInList());
        }
        if(StringUtils.isNotBlank(rsdfGamePropertyRecordQuery.getOrderByColumn())){
            if(rsdfGamePropertyRecordQuery.isAes()){
                wrapper.orderByAsc(rsdfGamePropertyRecordQuery.getOrderByColumn());
            }else{
                wrapper.orderByDesc(rsdfGamePropertyRecordQuery.getOrderByColumn());
            }
        }
        return wrapper;
    }
}